# Generated by Django 4.2.16 on 2024-09-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    ("facebook", "facebook"),
                    ("google", "google"),
                    ("twitter", "twitter"),
                    ("email", "email"),
                    ("github", "github"),
                ],
                default="email",
                max_length=255,
            ),
        ),
    ]
